### ISSUE TITLE
Possible Typo in fieldmanual/sphinx-docs /Getting-started.md

### ISSUE THREAD

**Issue by catbyte-io** [mitre/fieldmanual#123]
Hello, 
I was reading the documentation online and found a possible typo.
The Getting-started.md document says, "Log in as a red user. By default, a "red" user is creating with a password"...
I think the documentation is meant to say, "Log in as a red user. By default, a "red" user is created with a password"...
This is my first time contributing to a project that is not my own, and I would like to fix it if needs to be. Can I create a pull request?
Thank you so much for your time and for considering my request.

**Comment by clenk** [comment]
Hi @catbyte-io, yes looks like a good fix indeed! Please submit a PR and include any other typos you find, too.
